# This is a basic workflow to help you get started with Actions

name: Export From DEV

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      publishCustomizations:
        type: boolean
        description: Publish Customizations

env:
  SOLUTION_NAME: "['DemoSolution', 'SecondDemoSolution']"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Export:
    # The type of runner that the job will run on
    runs-on: windows-latest

    environment: DEV

    strategy:
      matrix: 
        solution: ["DemoSolution", "SecondDemoSolution"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      #- run: echo "URL ${{ vars.URL }}, TenantId ${{ vars.TENANTID }}, ClientID ${{ vars.CLIENTID }}, CliendSecret ${{ secrets.CLIENTSECRET }}!"
      
      - name: Publish Solution
        if: ${{ inputs.publishCustomizations == 'true' }}
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: ${{ vars.URL }}
          app-id: ${{ vars.CLIENTID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ vars.TENANTID }}
        
      - name: Export Solution - Unmanaged
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.URL }}
          app-id: ${{ vars.CLIENTID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ vars.TENANTID }}
          solution-name: ${{ matrix.solution }}
          solution-output-file: "${{runner.temp}}/exported/${{ matrix.solution }}.zip"
          managed: false
          run-asynchronously: true
          overwrite: true

      - name: Export Solution - Managed
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.URL }}
          app-id: ${{ vars.CLIENTID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ vars.TENANTID }}
          solution-name: ${{ matrix.solution }}
          solution-output-file: "${{runner.temp}}/exported/${{ matrix.solution }}_managed.zip"
          managed: false
          run-asynchronously: true
          overwrite: true
          
      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: '${{runner.temp}}/exported/${{ matrix.solution }}.zip'
          solution-folder: 'PowerPlatform/Solutions/${{ matrix.solution }}'
          solution-type: 'Both'
          overwrite-files: true

      # Commit all changed files back to the repository
      #- uses: stefanzweifel/git-auto-commit-action@v5
      - name: Commit Changes to Repo
        run: |
          git config user.email "<>"
          git config user.name "${{github.triggering_actor}}"
          git add 'PowerPlatform/Solutions/${{ matrix.solution }}' --all
          git commit -m "${{ matrix.solution }} Changes"
          git pull origin main
          git push origin main
