# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  workflow_run:
      workflows: ['Build Solution']
      types: [completed]
      branches:
          - 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ReleaseToTest:
    name: Release to Test
    
    # The type of runner that the job will run on
    runs-on: windows-latest

    environment: Test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: '${{runner.temp}}/artifacts'
          name: 'drop'
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Import Solution
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.URL }}
          app-id: ${{ vars.CLIENTID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ vars.TENANTID }}
          solution-file: '${{runner.temp}}/artifacts/DemoSolution_managed.zip'
          activate-plugins: true
          run-asynchronously: true
          use-deployment-settings-file: true
          deployment-settings-file: 'PowerPlatform/Solutions/Settings/DemoSolution-Test.json'
#          import-as-holding: true

 #     - name: Upgrade Solution
 #       uses: microsoft/powerplatform-actions/upgradde-solution@v1
 #       with:
 #         environment-url: ${{ vars.URL }}
 #         app-id: ${{ vars.CLIENTID }}
 #         client-secret: ${{ secrets.CLIENTSECRET }}
 #         tenant-id: ${{ vars.TENANTID }}
 #         solution-name: 'DemoSolution'
